### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by thibaultmol** [jstayton/suri#15]
Maybe this is a dumb question. But is it not possible to use Suri with Github pages instead?

**Comment by jstayton** [comment]
Hey  Thibault,

Yes, totally. You can use Suri anywhere you can deploy a static site, so GitHub Pages fits the bill.

While it's not based on Jekyll – and so won't be built automatically by GitHub – you should be able to use Actions to automate that. Or, of course, you can just build locally on your machine and push the generated static site up to your GitHub Pages branch.

I'm going to leave this open because I do want to add documentation about GitHub Pages to the README when I get a chance. Feel free to post back here with anything you find along the way as well!

**Comment by shirgoldbird** [comment]
This is exactly what I wanted to do. After some research I have it set up and working perfectly. This project is AMAZING. Thank you @jstayton :)

I followed [this guide](https://www.linkedin.com/pulse/eleventy-github-pages-lea-tortay/) for deploying Eleventy with GH Actions and made two changes.

1. Instead of creating a new SSH key, I used a GH token like so and then followed [these instructions](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token): `github_token: ${{ secrets.GITHUB_TOKEN }}`
2. I changed the directory to build from to `_site`: `publish_dir: ./_site`

**Comment by shirgoldbird** [comment]
One more change needed if you want to use a custom domain:

3. Add a CNAME file that contains your custom domain to the public folder.

Otherwise your custom domain will be removed on every build (oops)

**Comment by jstayton** [comment]
With the release of v1, there's now [a template repository for deploying to GitHub Pages](https://github.com/surishortlink/suri-deploy-github). It has everything configured to work in just a few steps.
