### ISSUE TITLE
[Q] Any way to use curl/wget a referenced file?

### ISSUE THREAD

**Issue by 1c383r9** [jstayton/suri#27]
Hi Jstayton!

Nice job on Suri!!

My question is: Is it possible to download a file that's pointed to by Suri?

Forgive my noobness.

Appreciate it!

**Comment by jstayton** [comment]
Hey @2ndMessiah – Sorry for the long delay. If you're still wondering about this, can you explain a bit more? Are you wanting to use cURL/Wget on the command line to download a file that's redirected to by Suri?

**Comment by 1c383r9** [comment]
> Hey @2ndMessiah – Sorry for the long delay. If you're still wondering about this, can you explain a bit more? Are you wanting to use cURL/Wget on the command line to download a file that's redirected to by Suri?

Thx for the reply. Yeah exactly. Now I would curl the shortened url to get the original url and curl it again to download it. Is there a better way? It's all good never mind:)

**Comment by jstayton** [comment]
The short URL will respond with [the HTML to do the redirect](https://github.com/jstayton/suri/blob/4ea9057c0ab625210adbe282510f5d155708fdaa/src/links.njk#L9-L14). You would need to parse the original URL out of that to then download it, since non-HTML environments like cURL/Wget don't automatically follow that type of redirect (as they do with `3xx` HTTP status codes, which Suri doesn't use).

Hope that helps!
